# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\riha_telemetry\"p\n\nTargetData\x12\x1d\n\x15\x64istanceHorizontalMax\x18\x01 \x01(\x02\x12\x1b\n\x13\x64istanceVerticalMax\x18\x02 \x01(\x02\x12&\n\x07targets\x18\x03 \x03(\x0b\x32\x15.iha_telemetry.Target\"J\n\x06Target\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1a\n\x12\x64istanceHorizontal\x18\x02 \x01(\x02\x12\x18\n\x10\x64istanceVertical\x18\x03 \x01(\x02\"\xa1\x03\n\nFlightData\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x02\x12\r\n\x05speed\x18\x04 \x01(\x02\x12\x0f\n\x07heading\x18\x05 \x01(\x02\x12\x0f\n\x07\x62\x61ttery\x18\x06 \x01(\x02\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x12\x0c\n\x04roll\x18\x08 \x01(\x02\x12\r\n\x05pitch\x18\t \x01(\x02\x12-\n\ntargetData\x18\n \x01(\x0b\x32\x19.iha_telemetry.TargetData\x12\x16\n\x0evertical_speed\x18\x0b \x01(\x02\x12\x0f\n\x07\x63urrent\x18\x0c \x01(\x02\x12\x0f\n\x07voltage\x18\r \x01(\x02\x12\x16\n\x0egps_satellites\x18\x0e \x01(\x05\x12\x10\n\x08gps_hdop\x18\x0f \x01(\x02\x12\x14\n\x0cgps_fix_type\x18\x10 \x01(\x05\x12\x13\n\x0b\x66light_mode\x18\x11 \x01(\t\x12\x13\n\x0bvibration_x\x18\x12 \x01(\x02\x12\x13\n\x0bvibration_y\x18\x13 \x01(\x02\x12\x13\n\x0bvibration_z\x18\x14 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TARGETDATA']._serialized_start=34
  _globals['_TARGETDATA']._serialized_end=146
  _globals['_TARGET']._serialized_start=148
  _globals['_TARGET']._serialized_end=222
  _globals['_FLIGHTDATA']._serialized_start=225
  _globals['_FLIGHTDATA']._serialized_end=642
# @@protoc_insertion_point(module_scope)
